import { Dimensions, StyleSheet } from 'react-native';

const { width: screenWidth } = Dimensions.get('window');
const isTablet = screenWidth > 768;

export const styles = StyleSheet.create({
  disabledButton: {
    backgroundColor: '#A5A5A5',
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 1,
    borderColor: '#c2c3cd',
    borderRadius: 4,
    marginRight: 8,
  },
  checkboxLabel: {
    fontSize: 14,
    color: '#111827',
  },
  container: {
    flex: 1,
    padding: 6,
    backgroundColor: '#F7FAFF',
  },
  safeArea: { flex: 1 },

  // sidebar
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 50,
    flexDirection: 'row',
    backgroundColor: '#F7FAFF',
  },
  backdrop: {
    flex: 1,
  },
  sidebar: {
    width: '100%',
    backgroundColor: '#F7FAFF',
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  logoCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  image: {
    flex: 1,
    width: '100%',
  },
  closeBtn: {
    marginLeft: 'auto',
    padding: 8,
  },
  menu: {
    marginTop: 24,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderRadius: 8,
  },
  menuIcon: {
    width: 28,
    alignItems: 'center',
    marginRight: 8,
  },
  menuLabel: {
    fontSize: 14,
    color: '#374151',
    fontWeight: '500',
  },
  footer: {
    marginTop: 'auto',
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  userBlock: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    fontWeight: '700',
    color: '#111827',
  },
  userName: {
    fontSize: 12,
    fontWeight: '600',
    color: '#111827',
  },
  userRole: {
    fontSize: 11,
    color: '#6B7280',
  },
  logoutBtn: {
    padding: 8,
    borderRadius: 8,
  },
  disabledBtn: {
    opacity: 0.5,
  },

  notificationContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    flex: 1,
  },
  pagination: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    backgroundColor: '#F7FAFF',
  },
  paginationButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#3657C3',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    gap: 4,
  },
  paginationButtonDisabled: {
    backgroundColor: '#9CA3AF',
  },
  paginationText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '500',
  },
  paginationInfo: {
    fontSize: 14,
    color: '#6B7280',
  },
  floatingChatButton: {
    position: 'absolute',
    bottom: 24,
    right: 4,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#3657C3',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  notificationCard: {
    backgroundColor: 'white',
    padding: 16,
    marginVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  notificationPressed: {
    backgroundColor: '#F3F4F6',
  },
  unreadNotification: {
    borderLeftWidth: 4,
    borderLeftColor: '#3657C3',
    backgroundColor: '#EEF2FF',
  },
  notificationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  unreadDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#3657C3',
    marginRight: 8,
  },
  notificationTitle: {
    fontSize: 15,
    flexShrink: 1,
    color: '#374151',
  },
  unreadTitle: {
    fontWeight: '700',
    color: '#111827',
  },
  notificationTime: {
    fontSize: 12,
    color: '#6B7280',
    marginLeft: 12,
  },
  Notificationheader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  headerText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
    marginLeft: 8,
  },
  unreadBadge: {
    marginLeft: 'auto',
    backgroundColor: '#3657C3',
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  unreadCount: {
    color: 'white',
    fontSize: 12,
    fontWeight: '600',
  },

  containerchat: {
    flex: 1,
  },
  containernotification: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 8,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  logo: { width: 120, height: 120 },
  greetingText: {
    fontSize: 24,
    fontWeight: '600',
    marginBottom: 12,
    textAlign: 'center',
  },
  tabletGreetingText: {
    fontSize: 28,
    marginBottom: 12,
  },
  noRouteContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 32,
    maxWidth: isTablet ? 600 : '100%',
  },
  webNoRouteContainer: {
    maxWidth: 800,
    paddingHorizontal: 40,
  },
  smallNoRouteContainer: {
    padding: 12,
  },
  instructionText: {
    fontSize: isTablet ? 20 : 16,
    color: '#6B7280',
    marginVertical: 8,
    textAlign: 'center',
  },
  tabletInstructionText: {
    fontSize: 22,
    marginVertical: 12,
  },
  selectRouteButton: {
    backgroundColor: '#3657C3',
    padding: isTablet ? 16 : 12,
    borderRadius: 8,
    marginTop: 16,
    minWidth: isTablet ? 300 : 250,
  },
  tabletSelectRouteButton: {
    padding: 20,
    borderRadius: 12,
    marginTop: 24,
  },
  selectRouteButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: isTablet ? 18 : 16,
    textAlign: 'center',
  },
  tabletSelectRouteButtonText: {
    fontSize: 20,
  },
  tabletFloatingChatButton: {
    padding: 18,
    borderRadius: 60,
    bottom: 30,
    right: 30,
  },
  accordion: { borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 8 },
  accordionTrigger: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 12,
    alignItems: 'center',
  },
  accordionTitle: { fontWeight: '600', fontSize: 16 },
  routeName: { color: '#374151', marginTop: 2 },
  accordionContent: { padding: 12, backgroundColor: 'white' },
  routeDetails: { marginBottom: 12 },
  detailText: { marginBottom: 4, fontSize: 14 },
  detailLabel: { fontWeight: '600' },
  badgeContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 4 },
  porterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    backgroundColor: '#e6e6ea',
    padding: 10,
    gap: 6,
    borderRadius: 12,
  },
  value: {
    fontSize: 16,
    flexShrink: 1,
    color: 'black',
  },
  badge: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 12,
    alignSelf: 'flex-start',
    backgroundColor: '#F7FAFF',
  },
  badgeText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
    padding: 6,
    borderRadius: 8,
    marginVertical: 6,
  },
  changeRouteButton: { backgroundColor: '#3657C3' },
  endDayButton: { backgroundColor: '#DC2626' },
  actionButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 14,
    flexDirection: 'row',
    gap: 8,
  },

  // Tickets
  ticketsSection: { marginTop: 16 },
  sectionTitle: { fontSize: 18, fontWeight: '700', marginBottom: 12 },

  ticketCard: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
    backgroundColor: '#fff',
  },
  ticketHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  ticketId: { fontWeight: '700', fontSize: 16 },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
  statusText: { fontSize: 12, fontWeight: '600' },
  ticketDetail: { fontSize: 14, marginBottom: 4 },
  ticketActions: { flexDirection: 'row', gap: 8 },
  ticketButton: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
    padding: 6,
    borderRadius: 8,
    marginHorizontal: 6,
    marginVertical: 6,
  },
  acceptButton: { backgroundColor: '#16A34A' },
  refuseButton: { backgroundColor: '#DC2626' },
  primaryButton: { backgroundColor: '#3657C3' },
  buttonText: { color: '#fff', fontWeight: '600' },
  backBtn: { padding: 6, borderRadius: 999, backgroundColor: '#F3F4F6' },
  headerTextWrap: { marginLeft: 12 },
  headerTitle: { fontSize: 16, fontWeight: '700', color: '#111827' },
  headerSubtitle: { fontSize: 12, color: '#6B7280' },
  badgeRow: { flexDirection: 'row', gap: 6, flexWrap: 'wrap', marginBottom: 8 },
  badgeTextDark: { fontSize: 12, fontWeight: '600', color: '#111827' },
  card: {
    backgroundColor: 'white',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 12,
    marginBottom: 12,
  },
  cardTitle: { fontWeight: '600', color: '#374151', marginBottom: 8, fontSize: 14 },
  gridRow: { flexDirection: 'row', gap: 12, justifyContent: 'space-between' },
  gridCol: { flex: 1 },
  muted: { fontSize: 12, color: '#6B7280' },
  smallLabel: { fontSize: 12, fontWeight: '600', color: '#111827' },
  note: { fontSize: 11, color: '#6B7280', marginTop: 2 },
  membersContainer: { flex: 1, backgroundColor: '#F7FAFF' },
  loadingImage: {
    width: 100,
    height: 100,
    marginBottom: 20,
  },
  loadingSpinner: {
    marginTop: 10,
  },
  searchInput: {
    margin: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 8,
    backgroundColor: '#fff',
  },
  membersList: { flex: 1 },
  memberItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderBottomWidth: 1,
    borderColor: '#E5E7EB',
  },
  statusDot: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#fff',
  },
  memberName: { fontWeight: '600', fontSize: 14 },
  memberRole: { fontSize: 12, color: '#6B7280' },
  chatContainer: { flex: 1 },
  chatHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderColor: '#E5E7EB',
  },
  chatTitle: { fontWeight: '600', fontSize: 16 },
  messages: { flex: 1, padding: 10 },
  messageBubble: { padding: 8, borderRadius: 8, marginVertical: 4, maxWidth: '70%' },
  messageLeft: { backgroundColor: '#E5E7EB', alignSelf: 'flex-start' },
  messageRight: { backgroundColor: '#3657C3', alignSelf: 'flex-end' },
  messageText: { color: '#111827' },
  messageTime: { fontSize: 10, color: '#6B7280', textAlign: 'right', marginTop: 2 },
  inputContainer: {
    flexDirection: 'row',
    padding: 8,
    borderTopWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#fff',
    alignItems: 'center',
  },
  messageInput: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 20,
    marginRight: 8,
  },
  sendBtn: {
    backgroundColor: '#3657C3',
    borderRadius: 20,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },

  logoContainer: {
    alignItems: 'center',
    marginBottom: 24,
  },
  tabletLogoContainer: {
    marginBottom: 32,
  },
  tabletLogo: {
    width: 150,
    height: 150,
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: '#111827',
  },
  subtitle: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 16,
  },

  formContainer: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  tabletFormContainer: {
    padding: 24,
    borderRadius: 16,
  },
  formTitle: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 16,
  },
  inputGroup: {
    marginBottom: 16,
  },
  label: {
    marginBottom: 8,
    fontWeight: '500',
  },
  inputWrapper: {
    position: 'relative',
  },
  icon: {
    position: 'absolute',
    left: 12,
    top: '50%',
    transform: [{ translateY: -10 }],
    zIndex: 1,
  },
  input: {
    borderWidth: 1,
    borderColor: '#c2c3cd',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    fontSize: 16,
    color: '#111827',
    backgroundColor: '#fff',
  },
  inputWithIcon: {
    paddingLeft: 45,
  },
  errorText: {
    color: '#EF4444',
    fontSize: 12,
    marginTop: 4,
  },
  button: {
    backgroundColor: '#3657C3',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
    marginTop: 16,
  },
  topBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  menuBtn: {
    padding: 6,
    borderRadius: 8,
  },
  TobBarlogo: {
    borderRadius: 6,
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  TobBartitle: {
    fontWeight: '700',
    fontSize: 16,
    color: '#111827',
  },
  TobBartabletTitle: {
    fontSize: 20,
  },
  TobBarsubtitle: {
    fontSize: 11,
    color: '#6B7280',
  },
  TobBartabletSubtitle: {
    fontSize: 13,
  },
  actions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  iconBtn: {
    padding: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(31,41,55,0.05)',
    marginLeft: 6,
  },
  iconBtnActive: {
    backgroundColor: '#3657C3',
  },
  disabled: {
    opacity: 0.4,
  },
  TobBarbadge: {
    position: 'absolute',
    top: -2,
    right: -2,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#EF4444',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  TobBarbadgeText: {
    color: 'white',
    fontSize: 10,
    fontWeight: '600',
  },
  content: { flex: 1 },
  retryButton: { backgroundColor: '#3657C3', padding: 10, borderRadius: 8, marginTop: 8 },
  retryButtonText: { color: 'white', fontWeight: '600' },
  emptyTitle: { fontSize: 16, fontWeight: '600', marginTop: 10, color: '#111827' },
  emptySubtitle: { fontSize: 14, color: '#6B7280' },
  tabsContainer: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#f8fafc',
  },
  tab: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginHorizontal: 4,
    borderRadius: 20,
    backgroundColor: '#e2e8f0',
  },
  tabActive: {
    backgroundColor: '#3657C3',
  },
  tabText: {
    fontSize: 14,
    color: '#64748b',
  },
  tabTextActive: {
    color: 'white',
    fontWeight: '600',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,
    marginVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#f8fafc',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  searchIcon: {
    marginRight: 8,
  },
  memberInfo: {
    flex: 1,
  },
  memberStatus: {
    fontSize: 12,
    color: '#6b7280',
    marginTop: 2,
  },
  unreadText: {
    color: 'white',
    fontSize: 12,
    fontWeight: '600',
  },
  paginationTextDisabled: {
    color: '#d1d5db',
  },
  closeButton: {
    margin: 16,
    paddingVertical: 12,
    backgroundColor: '#e2e8f0',
    borderRadius: 8,
    alignItems: 'center',
  },
  closeButtonText: {
    fontSize: 16,
    color: '#374151',
    fontWeight: '500',
  },
  typingText: {
    fontStyle: 'italic',
    color: '#6b7280',
  },
  aiSuggestions: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#f8fafc',
  },
  aiSuggestion: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginHorizontal: 4,
    backgroundColor: '#e2e8f0',
    borderRadius: 16,
  },
  aiSuggestionText: {
    fontSize: 12,
    color: '#374151',
  },
  chatHeaderInfo: {
    flex: 1,
    alignItems: 'center',
  },
  chatSubtitle: {
    fontSize: 12,
    color: '#6b7280',
    marginTop: 2,
  },
  chatHeaderButton: {
    padding: 4,
  },
  connectionStatus: {
    padding: 8,
    backgroundColor: '#fbbf24',
    alignItems: 'center',
  },
  connectionError: {
    backgroundColor: '#ef4444',
  },
  connectionText: {
    color: 'white',
    fontSize: 12,
    fontWeight: '500',
  },
});
